<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <RootNamespace>AzureZeng.MSBuildTasks.Json2Resources.Tests</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
        <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
        <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.8.2" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\MSBuildTasks.Json2Resources\Json2Resources.csproj" />
    </ItemGroup>
</Project>
